import { useCallback, useEffect, useMemo, useRef, useState, type MouseEvent, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from 'react'
import { Mosaic, MosaicWindow, type MosaicNode } from 'react-mosaic-component'
import {
  Aperture, Box, Boxes, Camera, Check, ChevronDown, ChevronRight, CircleDot, CloudSun, Code2, Crosshair,
  Database, FileBox, Filter, Folder, FolderOpen, Info, Layers3, Lightbulb, Link2, LoaderCircle, Maximize, Minimize2, Minus, MoreVertical,
  Play, Plus, RefreshCw, Search, Settings, Sparkles, Square, Trees, X, type LucideIcon,
} from 'lucide-react'
import clsx from 'clsx'
import { demoWorkspace } from './data/demo'
import type { AnalysisModule, AnalysisProgress, AnalysisResource, CaptureHistoryEntry, CapturePreset, CaptureProgress, CaptureProject, CompositionStage, RuntimeStatus, WorkspacePayload } from './data/types'
import './App.css'

type PanelId = 'outliner' | 'viewport' | 'timeline' | 'inspector'
const appVersion = '0.2.0'
const emptyModule: AnalysisModule = { module: 'auxiliary', displayName: '等待分析', confidence: 0, passNumber: 0, passName: '', eventStart: 0, eventEnd: 0, representativeEvent: 0, drawCount: 0, dispatchCount: 0, actionKind: 'none', totalIndices: 0, vertexShader: 0, fragmentShader: 0, computeShader: 0, outputs: [], textures: [], reasons: [], missing: [], previewPath: '', stages: [] }
const preferredModule = (workspace: WorkspacePayload) => workspace.modules.find(item => item.drawCount > 0) || workspace.modules[0] || emptyModule
const preferredStage = (module: AnalysisModule) => module.stages.find(item => item.eventId === module.representativeEvent) || module.stages[0] || null
const previewSource = (workspace: WorkspacePayload) => workspace.thumbnailDataUrl || demoWorkspace.thumbnailDataUrl
const moduleColors: Record<string, string> = { scene_geometry: '#48c98b', depth_shadow: '#e9b94c', sky_atmosphere: '#9d7cf5', transparent_effects: '#e76db1', compute_post: '#638fe6', ui: '#41cbd0', auxiliary: '#8797a1' }
const moduleLabels: Record<string, string> = { scene_geometry: '场景', depth_shadow: '深度', sky_atmosphere: '天空', transparent_effects: '透明', compute_post: '计算', ui: 'UI', auxiliary: '其他' }
const layout: MosaicNode<PanelId> = {
  type: 'split', direction: 'row', splitPercentages: [80, 20], children: [
    { type: 'split', direction: 'column', splitPercentages: [76, 24], children: ['viewport', 'timeline'] },
    'inspector',
  ],
}

const sceneRows = [
  [0, 'World（鸣潮）', 'world'], [1, 'Environment', 'folder'], [2, 'Landscape', 'landscape'], [2, 'Water', 'water'], [2, 'Sky', 'sky'], [2, 'VolumetricCloud', 'cloud'],
  [1, 'Geometry', 'folder'], [2, 'StaticMesh (342)', 'mesh'], [3, 'SM_Cliff_01', 'cube'], [3, 'SM_Ruin_A', 'cube'], [3, 'SM_Tower', 'cube'], [3, 'SM_Rock_Cluster', 'cube'], [3, 'SM_Tree_01', 'cube'],
  [1, 'Characters (18)', 'characters'], [2, 'CH_Player', 'person'], [2, 'CH_NPC_01', 'person'], [1, 'Effects (56)', 'effects'], [2, 'FX_Waterfall', 'effects'], [2, 'FX_Volumetric', 'effects'], [2, 'FX_Particles', 'effects'],
  [1, 'Lights (12)', 'light'], [2, 'DirLight_Sun', 'sun'], [2, 'Skylight', 'light'], [2, 'PointLight', 'light'], [1, 'UI (8)', 'ui'],
] as const

function iconFor(kind: string) {
  const props = { size: 14, strokeWidth: 1.7 }
  if (kind === 'folder') return <Folder {...props} />
  if (kind === 'mesh' || kind === 'world') return <Boxes {...props} />
  if (kind === 'cube') return <Box {...props} />
  if (kind === 'landscape') return <Trees {...props} />
  if (kind === 'water') return <CircleDot {...props} />
  if (kind === 'sky' || kind === 'cloud') return <CloudSun {...props} />
  if (kind === 'light' || kind === 'sun') return <Lightbulb {...props} />
  if (kind === 'effects') return <Sparkles {...props} />
  return <Layers3 {...props} />
}

function useModulePreview(workspace: WorkspacePayload, module: AnalysisModule) {
  const [loaded, setLoaded] = useState({ path: '', source: '' })
  useEffect(() => {
    let active = true
    if (!module.previewPath || !window.kiana) return () => { active = false }
    void window.kiana.loadImage(module.previewPath).then(value => { if (active) setLoaded({ path: module.previewPath, source: value }) }).catch(() => { /* fall back to the real RDC thumbnail below */ })
    return () => { active = false }
  }, [workspace.capturePath, module.previewPath])
  return module.previewPath && loaded.path === module.previewPath && loaded.source ? loaded.source : previewSource(workspace)
}

function useCompositionPreview(workspace: WorkspacePayload, module: AnalysisModule, stage: CompositionStage | null) {
  const fallback = useModulePreview(workspace, module)
  const [loaded, setLoaded] = useState({ key: '', source: '' })
  const eventId = stage?.eventId || 0
  const resourceId = stage?.outputResourceIds[0] || 0
  const stageName = stage?.name || ''
  const key = stage ? `${workspace.capturePath}:${eventId}:${resourceId}` : ''
  useEffect(() => {
    let active = true
    if (!eventId || !resourceId || !window.kiana) return () => { active = false }
    void window.kiana.previewStage(eventId, resourceId, stageName).then(value => {
      if (active) setLoaded({ key, source: value.dataUrl })
    }).catch(() => { /* keep the capture thumbnail while the live RT export is unavailable */ })
    return () => { active = false }
  }, [key, eventId, resourceId, stageName])
  if (!stage) return fallback
  if (key && loaded.key === key && loaded.source) return loaded.source
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="100%" height="100%" fill="#02070b"/><text x="50%" y="48%" text-anchor="middle" fill="#77dcec" font-family="Segoe UI, sans-serif" font-size="24">正在锁定 EID ${stage.eventId}</text><text x="50%" y="54%" text-anchor="middle" fill="#59717d" font-family="Segoe UI, sans-serif" font-size="15">从 RenderDoc 导出该步骤的真实 RT</text></svg>`)
}

const menuItems: Record<string, string[]> = { 项目: ['新建捕获项目','导入 RDC','保存工作区'], 编辑: ['复制事件路径'], 工具: ['自动分析','捕获 Unity 38112 基线','打开 Unity 工程','打开资产图谱','打开还原合同','打开高级 GPU 检查器','保存工作台快照','MCP 连接状态','偏好设置'], 视图: ['重置面板布局','最大化视口','场景浏览器','切换紧凑密度'], 窗口: ['最小化','最大化'], 帮助: ['快捷键','调试文档','关于 Kiana Studio'] }

function ActionIcon({ icon: Icon, tone = 'cyan' }: { icon: LucideIcon; tone?: 'cyan' | 'green' | 'amber' }) {
  return <span className={`action-icon tone-${tone}`}><Icon size={16} strokeWidth={2.25} /></span>
}

function TitleBar({ onAction, onCommand, runtime, workspace }: { onAction: (action: string) => void; onCommand: () => void; runtime: RuntimeStatus | null; workspace: WorkspacePayload }) {
  const [menu, setMenu] = useState('')
  return <header className="titlebar">
    <div className="brand"><span className="brand-mark">K</span><strong>Kiana Studio</strong></div>
    <nav className="app-menu">{Object.keys(menuItems).map(name => <button className={menu === name ? 'active' : ''} key={name} onClick={() => setMenu(current => current === name ? '' : name)}>{name}</button>)}</nav>
    <button className="mobile-menu-button" aria-label="应用菜单" onClick={() => setMenu(current => current === '全部' ? '' : '全部')}><MoreVertical size={17} /></button>
    {menu && <div className={clsx('menu-popup', menu === '全部' && 'mobile-popup')} style={{ left: menu === '全部' ? 56 : 196 + Object.keys(menuItems).indexOf(menu) * 52 }}><b>{menu === '全部' ? '应用菜单' : menu}</b>{menu === '全部' ? Object.entries(menuItems).map(([group, items]) => <div className="mobile-menu-group" key={group}><span>{group}</span>{items.map(item => <button key={item} onClick={() => { onAction(item); setMenu('') }}>{item}</button>)}</div>) : menuItems[menu].map(item => <button key={item} onClick={() => { onAction(item); setMenu('') }}>{item}</button>)}</div>}
    <button className="command-trigger" onClick={onCommand}><Search size={13} /><span>命令</span><kbd>Ctrl K</kbd></button>
    <button className={clsx('runtime-pill', runtime?.bridgeConnected && runtime?.unityMcp && 'connected')} onClick={() => onAction('MCP 连接状态')} title={runtime?.kianaRoot || '正在检测 Kiana RenderDoc'}><CircleDot size={12} />{runtime?.bridgeConnected && runtime?.unityMcp ? `双 MCP 在线 · ${runtime.mcpTools} tools` : runtime?.bridgeConnected ? 'RenderDoc MCP 在线' : runtime?.unityMcp ? 'Unity MCP 在线' : runtime?.connected ? 'RenderDoc 就绪' : '运行时未就绪'}</button>
    <div className="system-stats"><span>API <b>{workspace.api}</b></span><span>Draws {workspace.coverage.frameDraws}</span><span>Pass {workspace.coverage.passes}</span></div>
    <button className="icon-button" aria-label="设置" onClick={() => onAction('偏好设置')}><Settings size={15} /></button>
    <div className="window-buttons"><button onClick={() => window.kiana?.minimize()} aria-label="最小化"><Minimize2 size={14} /></button><button onClick={() => window.kiana?.maximize()} aria-label="最大化"><Square size={12} /></button><button className="window-close" onClick={() => window.kiana?.close()} aria-label="关闭"><X size={15} /></button></div>
  </header>
}

function Pipeline({ workspace, runtime, progress, captureArmed, busy, onCapture, onTrigger, onAnalyze, onExport }: { workspace: WorkspacePayload; runtime: RuntimeStatus | null; progress: AnalysisProgress | null; captureArmed: boolean; busy: boolean; onCapture: () => void; onTrigger: () => void; onAnalyze: () => void; onExport: () => void }) {
  const hasCapture = workspace.mode === 'capture'
  const hasPackage = hasCapture && Boolean(workspace.manifestPath)
  const canAnalyze = hasCapture && Boolean(runtime?.python && runtime.analysisWorker)
  const captureProgress = progress as CaptureProgress | null
  const showSession = Boolean(captureProgress?.sessionActive) && captureProgress?.phase !== 'failed'
  const sessionLabel = captureProgress?.phase === 'launching' ? '正在启动 / 注入' : captureArmed ? '已连接，可抓帧' : captureProgress?.phase === 'capturing' ? '正在保存当前帧' : captureProgress?.phase === 'verifying' ? '正在验证 RDC' : captureProgress?.phase === 'analyzing' ? '正在自动分析' : captureProgress?.phase === 'failed' ? '连接已断开' : '未连接游戏'
  return <div className="pipeline"><div className="action-group"><button className="dcs-btn dcs-btn--primary icon-action" onClick={onCapture}><ActionIcon icon={Camera} />启动 / 注入游戏</button><button className={clsx('dcs-btn icon-action capture-frame-button', captureArmed && 'capture-armed')} disabled={!captureArmed} title={captureArmed ? `截取 ${captureProgress?.projectName || '当前游戏'} 的当前画面并保存 RDC` : progress?.message || '先启动并注入游戏，等待实时会话连接成功'} onClick={onTrigger}><ActionIcon icon={Crosshair} tone={captureArmed ? 'green' : 'amber'} />{captureArmed ? '截取当前游戏帧' : '等待游戏连接'}</button><button className="dcs-btn icon-action" title={!hasCapture ? '请先导入 RDC' : !canAnalyze ? '分析运行时尚未就绪' : ''} onClick={onAnalyze} disabled={busy || !canAnalyze}><ActionIcon icon={Play} tone="green" />{busy ? '任务运行中…' : 'AI 自动逆向'}</button></div>
    {showSession && <div className={clsx('capture-session-chip', 'live', captureArmed && 'armed')} title={captureProgress?.outputDirectory || '启动并注入游戏后，这里显示真实捕获目标'}><span className="capture-session-dot" /><div><b>{captureProgress?.projectName || '实时捕获会话'}</b><small>{sessionLabel}{captureProgress?.targetPid ? ` · PID ${captureProgress.targetPid}` : ''}{captureProgress?.api ? ` · ${captureProgress.api}` : ''}</small></div></div>}
    <button className="dcs-btn dcs-btn--primary export icon-action" disabled={!hasPackage} title={!hasPackage ? '导入真实 RDC 并完成分析后可打开' : ''} onClick={onExport}><ActionIcon icon={FileBox} />打开分析包</button></div>
}

function ProjectRail({ workspace, history, collapsed, openingCapturePath, onToggle, onImport, onNew, onSelectModule, onOpenPackage, onOpenAssetGraph, onOpenContract, onOpenCapture, onOpenCaptureRoot, activeFrame }: { workspace: WorkspacePayload; history: CaptureHistoryEntry[]; collapsed: boolean; openingCapturePath: string; onToggle: () => void; onImport: () => void; onNew: () => void; onSelectModule: (module: AnalysisModule) => void; onOpenPackage: () => void; onOpenAssetGraph: () => void; onOpenContract: () => void; onOpenCapture: (capturePath: string) => void; onOpenCaptureRoot: () => void; activeFrame: number }) {
  const [capturesOpen, setCapturesOpen] = useState(true); const [rebuildOpen, setRebuildOpen] = useState(false); const [openFolders, setOpenFolders] = useState<Set<string>>(new Set(['Passes']))
  const captureTitle = workspace.mode === 'demo' ? '演示工作区' : workspace.captureName.replace(/\.rdc$/i, '')
  const folders = [
    { key: 'Passes', count: workspace.coverage.passes, items: workspace.modules.map(module => ({ label: `#${module.passNumber} ${module.displayName}`, module })) },
    { key: 'Modules', count: workspace.coverage.modules, items: workspace.modules.map(module => ({ label: `${module.displayName} · EID ${module.representativeEvent || module.eventEnd}`, module })) },
    { key: 'Evidence', count: workspace.coverage.evidenceExports, items: workspace.modules.filter(module => module.reasons.length).map(module => ({ label: module.reasons[0], module })) },
    { key: 'Geometry', count: workspace.coverage.geometryExports, items: workspace.modules.filter(module => module.totalIndices > 0).map(module => ({ label: `${module.displayName} · ${module.totalIndices.toLocaleString()} indices`, module })) },
    { key: 'Textures', count: workspace.modules.reduce((sum, module) => sum + module.textures.length, 0), items: workspace.modules.flatMap(module => module.textures.map(texture => ({ label: texture.name || `${texture.slot} ${texture.role}`, module }))) },
  ]
  const toggleFolder = (key: string) => setOpenFolders(current => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next })
  return <aside className="project-rail"><button className="rail-heading" onClick={onToggle} title={collapsed ? '展开项目栏' : '折叠项目栏'}><Folder size={15} /><span>项目</span>{collapsed ? <ChevronRight size={15} /> : <ChevronDown size={15} />}</button><div className="rail-scroll"><div className="project-name"><Camera size={15} />{captureTitle} · Frame {activeFrame}</div>
    <div className="project-root"><img src={previewSource(workspace)} alt="捕获预览" /><div><b>{captureTitle}</b><span title={workspace.capturePath}>{workspace.mode === 'demo' ? '导入 RDC 以连接真实数据' : workspace.capturePath}</span></div></div><div className="capture-history-heading"><button className="rail-section" onClick={() => setCapturesOpen(value => !value)}>{capturesOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}<Folder size={14} />捕获历史 ({history.length})</button><button className="capture-root-button" onClick={onOpenCaptureRoot} title="打开当前游戏的完整捕获文件夹" aria-label="打开捕获总目录"><FolderOpen size={14} /></button></div>
    {capturesOpen && <div className="capture-history">{history.length ? history.slice(0, 30).map(item => { const opening = openingCapturePath === item.capturePath; return <div key={item.capturePath} className={clsx('capture-history-row', item.capturePath === workspace.capturePath && 'selected', opening && 'loading')} aria-busy={opening}><button className="capture-history-open" onClick={() => onOpenCapture(item.capturePath)} disabled={Boolean(openingCapturePath)} title={`在 Studio 中打开 · ${item.capturePath}`}><span><b>Frame {item.frameNumber || '—'}</b><em>{opening ? <><LoaderCircle size={11} />正在打开…</> : item.analyzed ? '已分析' : '待分析'}</em></span><small>{item.captureName} · {(item.captureBytes / 1024 / 1024).toFixed(1)} MB</small></button></div> }) : <div className="capture-history-empty">未发现历史 RDC</div>}</div>}<div className="rail-divider" /><button className="rail-section" onClick={() => setRebuildOpen(value => !value)}>{rebuildOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}<Database size={14} />分析工程</button>
    {rebuildOpen && <><button className="tree-row" onDoubleClick={onOpenPackage} title="双击打开真实分析目录"><ChevronDown size={13} /><Box size={13} />Analysis Package</button>{workspace.assetGraph?.path && <div className="reverse-summary"><button onClick={onOpenAssetGraph} title={workspace.assetGraph.path}><Database size={13} /><span>资产图谱</span><b>{workspace.assetGraph.objects} 对象</b></button><button onClick={onOpenContract} disabled={!workspace.reconstructionContract?.path} title={workspace.reconstructionContract?.path || '需要重新运行自动分析'}><Code2 size={13} /><span>还原合同</span><b>{workspace.reconstructionContract?.path ? '已生成' : '待生成'}</b></button><div><span>角色 {workspace.reconstructionContract?.counts.characters || workspace.assetGraph.characterEventIds.length}</span><span>环境 {workspace.reconstructionContract?.counts.environment || 0}</span><span>材质 {workspace.assetGraph.materials}</span><span>Shader {workspace.assetGraph.shaders}</span></div></div>}{folders.map(folder => <div className="rail-folder" key={folder.key}><button onClick={() => toggleFolder(folder.key)} className={clsx('tree-row child', openFolders.has(folder.key) && 'selected')}><span className="disclosure">{openFolders.has(folder.key) ? <ChevronDown size={12} /> : <ChevronRight size={12} />}</span><Folder size={13} />{folder.key} ({folder.count})</button>{openFolders.has(folder.key) && <div className="rail-folder-items">{folder.items.length ? folder.items.slice(0, 30).map((item, index) => <button key={`${item.label}-${index}`} title={item.label} onClick={() => onSelectModule(item.module)}><CircleDot size={9} /><span>{item.label}</span></button>) : <button className="empty" onClick={onOpenPackage}>没有导出项 · 打开分析目录</button>}</div>}</div>)}</>}
    </div><div className="rail-actions"><button className="dcs-btn rail-button" onClick={onImport}><Plus size={14} />导入 RDC</button><button className="dcs-btn rail-button" onClick={onNew}><Plus size={14} />新建项目</button></div></aside>
}

function SceneOutliner({ workspace, selected, onSelect }: { workspace: WorkspacePayload; selected: string; onSelect: (name: string, module?: AnalysisModule) => void }) {
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set()); const [activeTab, setActiveTab] = useState<'scene' | 'resources'>('scene'); const [query, setQuery] = useState('')
  const toggleCollapsed = (event: MouseEvent, name: string) => { event.stopPropagation(); setCollapsed(current => { const next = new Set(current); if (next.has(name)) next.delete(name); else next.add(name); return next }) }
  const rows = useMemo(() => workspace.mode === 'capture' && workspace.modules.length ? ([[0, `${workspace.captureName} · Frame ${workspace.frameNumber}`, 'world'], ...workspace.modules.map((module, index) => [1, `${module.displayName} · EID ${module.representativeEvent || module.eventEnd}`, index ? 'layers' : 'mesh'] as const)] as const) : sceneRows, [workspace])
  const filteredRows = useMemo(() => {
    if (query.trim()) return rows.filter(([, name]) => name.toLowerCase().includes(query.trim().toLowerCase()))
    const ancestors: string[] = []
    return rows.filter(([level, name]) => { ancestors.length = level; const visible = !ancestors.some(parent => collapsed.has(parent)); ancestors[level] = name; return visible })
  }, [collapsed, query, rows])
  const textureCount = workspace.assetGraph?.textures || workspace.modules.reduce((sum, module) => sum + module.textures.length, 0)
  const outputCount = workspace.modules.reduce((sum, module) => sum + module.outputs.length, 0)
  const shaderCount = workspace.assetGraph?.shaders || new Set(workspace.modules.flatMap(module => [module.vertexShader, module.fragmentShader, module.computeShader]).filter(Boolean)).size
  const resources = [['对象候选',String(workspace.assetGraph?.objects || 0),'box'],['材质族',String(workspace.assetGraph?.materials || 0),'layers'],['纹理',String(textureCount),'image'],['输出资源',String(outputCount),'layers'],['Shader',String(shaderCount),'code'],['角色候选',String(workspace.assetGraph?.characterEventIds.length || 0),'person'],['Draw Calls',String(workspace.coverage.frameDraws),'box'],['Indexed Actions',String(workspace.coverage.indexedActions),'database']].filter(([name]) => name.toLowerCase().includes(query.trim().toLowerCase()))
  return <section className="panel-content outliner"><div className="panel-tabs"><button className={activeTab === 'scene' ? 'active' : ''} onClick={() => setActiveTab('scene')}>场景</button><button className={activeTab === 'resources' ? 'active' : ''} onClick={() => setActiveTab('resources')}>资源</button><MoreVertical size={15} /></div><label className="search"><Search size={14} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder={activeTab === 'scene' ? '搜索场景对象…' : '搜索捕获资源…'} /></label>
    {activeTab === 'scene' ? <div className="scene-tree">{filteredRows.map(([level, name, kind]) => { const expandable = workspace.mode === 'capture' ? level === 0 : kind !== 'cube' && kind !== 'person'; const module = workspace.modules.find(item => name.endsWith(`EID ${item.representativeEvent || item.eventEnd}`)); return <button key={name} onClick={() => onSelect(name, module)} className={clsx('scene-row', selected === name && 'selected')} style={{ paddingLeft: 8 + (query ? 0 : level * 15) }}>{expandable ? <span className="disclosure" onClick={event => toggleCollapsed(event, name)}>{collapsed.has(name) ? <ChevronRight size={12} /> : <ChevronDown size={12} />}</span> : <span className="indent-line" />}{iconFor(kind)}<span>{name}</span></button>})}</div> : <div className="resource-browser">{resources.map(([name,count,kind]) => <div className="resource-summary" key={name}>{iconFor(kind)}<span>{name}</span><b>{count}</b></div>)}</div>}</section>
}

function Viewport({ workspace, selected, selectedStage, selectedObject, frame, maximized, resource, onCloseResource, onMaximize, onSnapshot, onNotify }: { workspace: WorkspacePayload; selected: AnalysisModule; selectedStage: CompositionStage | null; selectedObject: string; frame: number; maximized: boolean; resource: AnalysisResource | null; onCloseResource: () => void; onMaximize: () => void; onSnapshot: () => void; onNotify: (message: string) => void }) {
  const imageRef = useRef<HTMLImageElement>(null)
  const dragRef = useRef<{ pointerId: number; clientX: number; clientY: number; x: number; y: number } | null>(null)
  const draggedRef = useRef(false)
  const imageSource = useCompositionPreview(workspace, selected, selectedStage)
  const [overlay, setOverlay] = useState(true); const [fitImage, setFitImage] = useState(true); const [viewTransform, setViewTransform] = useState({ scale: 1, x: 0, y: 0 }); const [panning, setPanning] = useState(false); const [pixel, setPixel] = useState<{ x: number; y: number; rgba: number[] } | null>(null); const [histogram, setHistogram] = useState<number[] | null>(null)
  const resetView = useCallback((fit = true) => { setViewTransform({ scale: 1, x: 0, y: 0 }); setFitImage(fit); setPixel(null) }, [])
  const zoomBy = (factor: number) => setViewTransform(current => { const scale = Math.min(8, Math.max(.25, current.scale * factor)); const ratio = scale / current.scale; return { scale, x: current.x * ratio, y: current.y * ratio } })
  const zoomAtCursor = (event: ReactWheelEvent<HTMLElement>) => {
    if ((event.target as HTMLElement).closest('.viewport-toolbar')) return
    event.preventDefault()
    const rect = event.currentTarget.getBoundingClientRect()
    const contentHeight = Math.max(1, rect.height - 36)
    const cursorX = event.clientX - rect.left - rect.width / 2
    const cursorY = event.clientY - rect.top - contentHeight / 2
    setViewTransform(current => {
      const nextScale = Math.min(8, Math.max(.25, current.scale * Math.exp(-event.deltaY * .0015)))
      const ratio = nextScale / current.scale
      return { scale: nextScale, x: cursorX - (cursorX - current.x) * ratio, y: cursorY - (cursorY - current.y) * ratio }
    })
  }
  const beginPan = (event: ReactPointerEvent<HTMLImageElement>) => {
    if (event.button !== 0 || viewTransform.scale <= 1) return
    event.currentTarget.setPointerCapture(event.pointerId); draggedRef.current = false
    dragRef.current = { pointerId: event.pointerId, clientX: event.clientX, clientY: event.clientY, x: viewTransform.x, y: viewTransform.y }; setPanning(true)
  }
  const movePan = (event: ReactPointerEvent<HTMLImageElement>) => {
    const drag = dragRef.current; if (!drag || drag.pointerId !== event.pointerId) return
    const dx = event.clientX - drag.clientX; const dy = event.clientY - drag.clientY
    if (Math.abs(dx) + Math.abs(dy) > 3) draggedRef.current = true
    setViewTransform(current => ({ ...current, x: drag.x + dx, y: drag.y + dy }))
  }
  const endPan = (event: ReactPointerEvent<HTMLImageElement>) => { if (dragRef.current?.pointerId !== event.pointerId) return; dragRef.current = null; setPanning(false); event.currentTarget.releasePointerCapture?.(event.pointerId) }
  const samplePixel = (event: MouseEvent<HTMLImageElement>) => { if (draggedRef.current) { draggedRef.current = false; return } if (!imageRef.current) return; const image = imageRef.current; const rect = image.getBoundingClientRect(); const x = Math.max(0, Math.min(image.naturalWidth - 1, Math.floor((event.clientX - rect.left) * image.naturalWidth / rect.width))); const y = Math.max(0, Math.min(image.naturalHeight - 1, Math.floor((event.clientY - rect.top) * image.naturalHeight / rect.height))); const canvas = document.createElement('canvas'); canvas.width = 1; canvas.height = 1; const context = canvas.getContext('2d'); context?.drawImage(image, x, y, 1, 1, 0, 0, 1, 1); setPixel({ x, y, rgba: Array.from(context?.getImageData(0, 0, 1, 1).data || []) }); onNotify(`导出图像像素 (${x}, ${y}) 已读取`) }
  const toggleHistogram = () => { if (histogram) return setHistogram(null); const image = imageRef.current; if (!image?.naturalWidth) return; const canvas = document.createElement('canvas'); canvas.width = 128; canvas.height = 72; const context = canvas.getContext('2d'); context?.drawImage(image, 0, 0, 128, 72); const bins = new Array(32).fill(0) as number[]; const data = context?.getImageData(0, 0, 128, 72).data || []; for (let i = 0; i < data.length; i += 4) bins[Math.min(31, Math.floor((data[i] * .2126 + data[i + 1] * .7152 + data[i + 2] * .0722) / 8))] += 1; setHistogram(bins) }
  const actionLabel = selected.actionKind === 'dispatch' ? `Dispatches ${selected.dispatchCount}` : `Draw Calls ${selected.drawCount}`
  if (resource) return <section className="viewport-document"><div className="document-tabs"><button onClick={onCloseResource}>帧输出 · EID {selected.representativeEvent || selected.eventEnd}</button><button className="active"><Database size={13} />纹理查看器 · {resource.name}<X size={12} onClick={event => { event.stopPropagation(); onCloseResource() }} /></button></div><ResourceViewer resource={resource} onClose={onCloseResource} /></section>
  const liveEvent = selectedStage?.eventId || selected.representativeEvent || selected.eventEnd
  const internalRenderTarget = Boolean(selectedStage && !selectedStage.outputResourceIds.includes(1181))
  const surfaceLabel = selected.module === 'ui' ? '最终画面 / UI 逐层合成' : selected.module === 'scene_geometry' ? 'G-buffer 写入' : selected.module === 'compute_post' ? '预计算 / 辅助资源' : internalRenderTarget ? '离屏合成 RT' : '屏幕合成输出'
  return <section className={clsx('viewport', overlay && 'show-overlay', fitImage && 'fit-image', panning && 'is-panning', viewTransform.scale > 1 && 'can-pan', internalRenderTarget && 'internal-render-target')} onWheel={zoomAtCursor}><img ref={imageRef} onClick={samplePixel} onDoubleClick={() => resetView(true)} onPointerDown={beginPan} onPointerMove={movePan} onPointerUp={endPan} onPointerCancel={endPan} className="viewport-image" src={imageSource} alt={`真实合成步骤 · EID ${liveEvent}`} draggable={false} style={{ transform: `translate3d(${viewTransform.x}px, ${viewTransform.y}px, 0) scale(${viewTransform.scale})${internalRenderTarget ? ' scaleY(-1)' : ''}` }} /><div className="viewport-hud"><b>{workspace.api} · EID 锁定输出</b><span>{selectedStage ? selectedStage.name : selected.displayName}</span><span>{surfaceLabel}{internalRenderTarget ? ' · Y 方向已校正' : ''}</span><span>Frame {frame} · EID {liveEvent}</span><span>{selectedStage ? `${selectedStage.kind === 'dispatch' ? 'Dispatch' : 'Draw'} ${selectedStage.ordinal}` : actionLabel}</span><span>Indices {(selectedStage?.numIndices || selected.totalIndices).toLocaleString()}</span><span>{selectedStage?.outputResourceIds.length || selected.outputs.length} Outputs · {selected.textures.length} Textures</span></div>
    <div className="viewport-tools"><button aria-label="保存工作台快照" title="保存工作台快照" onClick={onSnapshot}><span className="tool-glyph"><Camera size={17} strokeWidth={2.1} /></span></button></div><div className="selection-label"><b>{selectedObject}</b><span>Indices&nbsp; {selected.totalIndices.toLocaleString()}</span><span>{selected.actionKind === 'dispatch' ? 'Dispatches' : 'Draws'}&nbsp; {selected.actionKind === 'dispatch' ? selected.dispatchCount : selected.drawCount}</span><span>Resources&nbsp; {selected.outputs.length + selected.textures.length}</span></div>
    {pixel && <div className="pixel-readout">({pixel.x}, {pixel.y}) · RGBA {pixel.rgba.join(', ')}</div>}{histogram && <div className="histogram" aria-label="亮度直方图">{histogram.map((value, index) => <i key={index} style={{ height: `${Math.max(2, value / Math.max(...histogram) * 100)}%` }} />)}</div>}
    <div className="viewport-toolbar"><button className={overlay ? 'active' : ''} title="切换真实数据叠加层" aria-label="切换叠加层" onClick={() => setOverlay(value => !value)}><Info size={15} /></button><span className="real-data-badge"><Check size={12} /><span>RenderDoc 真实输出</span></span><span className="viewport-gesture-hint">滚轮缩放 · 拖拽平移 · 双击适配</span><span className="toolbar-grow" /><button title="缩小" aria-label="缩小视图" onClick={() => zoomBy(1 / 1.25)}><Minus size={14} /></button><button className="viewport-zoom-label" title="恢复 100%" onClick={() => setViewTransform({ scale: 1, x: 0, y: 0 })} aria-live="polite">{Math.round(viewTransform.scale * 100)}%</button><button title="放大" aria-label="放大视图" onClick={() => zoomBy(1.25)}><Plus size={14} /></button><button title="适配整个帧" className={fitImage && viewTransform.scale === 1 ? 'active' : ''} onClick={() => resetView(true)}>适配</button><button title="重置到 1:1" onClick={() => resetView(false)}>1:1</button><button title="导出图像亮度直方图" className={histogram ? 'active' : ''} aria-label="打开直方图" onClick={toggleHistogram}><Aperture size={15} /></button><button title="保存工作台快照" aria-label="保存工作台快照" onClick={onSnapshot}><Camera size={15} /></button><button title={maximized ? '恢复工作台' : '最大化视口'} className={maximized ? 'active' : ''} onClick={onMaximize} aria-label={maximized ? '恢复工作台' : '最大化视口'}><Maximize size={15} /></button></div></section>
}

function Timeline({ workspace, selected, selectedStage, frame, onSelect, onSelectStage }: { workspace: WorkspacePayload; selected: AnalysisModule; selectedStage: CompositionStage | null; frame: number; onSelect: (module: AnalysisModule) => void; onSelectStage: (stage: CompositionStage) => void }) {
  const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [moduleFilter, setModuleFilter] = useState<Set<string>>(new Set())
  const next = () => { if (!workspace.modules.length) return; const index = workspace.modules.findIndex(module => module.passNumber === selected.passNumber); onSelect(workspace.modules[(index + 1) % workspace.modules.length]) }
  const moduleTypes = Array.from(new Set(workspace.modules.map(module => module.module)))
  const toggleFilter = (key: string) => setModuleFilter(current => { const next = new Set(current); if (key === 'all') return new Set(); if (next.has(key)) next.delete(key); else next.add(key); return next })
  const filtered = workspace.modules.filter(module => (module.drawCount || module.dispatchCount || module.representativeEvent) && (!moduleFilter.size || moduleFilter.has(module.module)) && (!query.trim() || `${module.passNumber} ${module.displayName} ${module.passName} ${module.representativeEvent}`.toLowerCase().includes(query.trim().toLowerCase())))
  const selectedActions = selected.actionKind === 'dispatch' ? `${selected.dispatchCount} Dispatches` : `${selected.drawCount} Draws`
  return <section className="timeline-panel"><div className="timeline-head"><b>Pass Timeline</b><span className="eid">EID {selected.representativeEvent || selected.eventEnd}</span><button title="下一个 Pass" onClick={next} aria-label="下一个 Pass"><ChevronRight size={14} /></button><button title="搜索 Pass" className={searchOpen ? 'active' : ''} onClick={() => setSearchOpen(value => !value)} aria-label="搜索 Pass"><Search size={14} /></button>{searchOpen && <input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="EID / Pass" />}<span>Frame {frame}</span><b>{selectedActions}</b></div><div className="timeline-filters"><Filter size={13} /><button className={!moduleFilter.size ? 'active' : ''} onClick={() => toggleFilter('all')}><i />全部</button>{moduleTypes.map(key => <button className={moduleFilter.has(key) ? 'active' : ''} onClick={() => toggleFilter(key)} key={key}><i style={{ background: moduleColors[key] }} />{moduleLabels[key] || key}</button>)}</div><div className="timeline-strip">{workspace.modules.map(module => <button className={moduleFilter.size && !moduleFilter.has(module.module) ? 'filtered-out' : ''} key={module.passNumber} onClick={() => onSelect(module)} style={{ flex: Math.max(1, module.drawCount || module.dispatchCount), background: moduleColors[module.module] || '#667' }} title={module.passName} />)}</div>
    <div className="timeline-body"><div className="pass-table"><div className="pass-row pass-header"><span>#</span><span>Pass Name</span><span>EID</span><span>Actions</span><span>Indices</span><span>Confidence</span></div>{filtered.map(module => <button className={clsx('pass-row', selected.passNumber === module.passNumber && 'selected')} onClick={() => onSelect(module)} key={module.passNumber}><span>{module.passNumber}</span><span><i style={{ background: moduleColors[module.module] }} />{module.displayName}</span><span>{module.representativeEvent || '—'}</span><span>{module.actionKind === 'dispatch' ? `${module.dispatchCount} CS` : module.drawCount}</span><span>{module.totalIndices ? `${(module.totalIndices / 1000).toFixed(1)} K` : '—'}</span><span>{Math.round(module.confidence * 100)}%</span></button>)}{filtered.length === 0 && <div className="pass-empty">没有匹配的 Pass</div>}</div>
      <div className="pass-evidence composition-browser"><div className="composition-title"><b>Pass {selected.passNumber} · 合成步骤</b><span>{selected.stages.length} 个可定位动作</span></div><div className="composition-stages">{selected.stages.map(stage => <button key={stage.eventId} className={clsx('composition-stage', selectedStage?.eventId === stage.eventId && 'selected')} onClick={() => onSelectStage(stage)}><span className="stage-order">{String(stage.ordinal).padStart(2, '0')}</span><span><b>{stage.name}</b><small>{stage.bindingName ? `${stage.bindingName} · ` : ''}EID {stage.eventId} · RID {stage.outputResourceIds.join(', ') || '—'}</small></span><em>{stage.kind === 'dispatch' ? 'CS' : stage.kind === 'clear' ? 'Clear' : stage.kind === 'copy' ? 'Copy' : stage.kind === 'present' ? 'Present' : `${stage.numIndices.toLocaleString()} idx`}</em></button>)}{selected.stages.length === 0 && <div className="pass-empty">此 Pass 没有可定位的合成动作</div>}</div><div className="composition-footer">选择步骤后从 RenderDoc 按该 EID 即时导出真实 RT，不使用最终帧代替。</div></div></div></section>
}

function ResourceViewer({ resource, onClose }: { resource: AnalysisResource; onClose: () => void }) {
  const [preview, setPreview] = useState<{ path: string; dataUrl: string; result: Record<string, unknown> } | null>(null)
  const [error, setError] = useState(resource.resourceId ? '' : '这个旧分析包没有保存 Resource ID；请对该 RDC 重新运行“AI 自动逆向”。')
  const [channel, setChannel] = useState<'RGB' | 'R' | 'G' | 'B' | 'A'>('RGB')
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  useEffect(() => {
    let active = true
    if (!resource.resourceId) return () => { active = false }
    void window.kiana?.previewTexture(resource.resourceId, resource.name).then(value => { if (active) setPreview(value) }).catch(reason => { if (active) { const raw = reason instanceof Error ? reason.message : String(reason); const concise = raw.match(/RuntimeError:\s*([^\r\n]+)/)?.[1] || raw.split(/\r?\n/)[0]; setError(concise.slice(0, 240)) } })
    return () => { active = false }
  }, [resource])
  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas || !preview?.dataUrl) return
    const image = new Image()
    image.onload = () => {
      canvas.width = image.naturalWidth; canvas.height = image.naturalHeight
      const context = canvas.getContext('2d', { willReadFrequently: true }); if (!context) return
      context.drawImage(image, 0, 0)
      const pixels = context.getImageData(0, 0, canvas.width, canvas.height)
      for (let i = 0; i < pixels.data.length; i += 4) {
        const value = channel === 'R' ? pixels.data[i] : channel === 'G' ? pixels.data[i + 1] : channel === 'B' ? pixels.data[i + 2] : channel === 'A' ? pixels.data[i + 3] : 0
        if (channel !== 'RGB') pixels.data[i] = pixels.data[i + 1] = pixels.data[i + 2] = value
        pixels.data[i + 3] = 255
      }
      context.putImageData(pixels, 0, 0)
    }
    image.src = preview.dataUrl
  }, [preview?.dataUrl, channel])
  return <section className="resource-preview-dialog embedded" aria-label={`资源预览 ${resource.name}`}><header><div><Database size={18} /><span><b>{resource.name || '未命名资源'}</b><small>Resource ID {resource.resourceId || '未记录'} · {resource.slot} · {resource.role}</small></span></div><nav className="resource-channels" aria-label="预览通道">{(['RGB','R','G','B','A'] as const).map(value => <button className={channel === value ? 'active' : ''} onClick={() => setChannel(value)} key={value}>{value}</button>)}</nav><button onClick={onClose} aria-label="关闭资源标签"><X size={17} /></button></header><div className="resource-preview-body">{preview?.dataUrl ? <canvas ref={canvasRef} aria-label={`${resource.name} ${channel} 通道预览`} /> : <div className={clsx('resource-preview-loading', error && 'failed')}>{error || '正在通过 RenderDoc 导出真实资源…'}</div>}<aside><div><span>尺寸</span><b>{resource.width || '—'} × {resource.height || '—'}</b></div><div><span>格式</span><b>{resource.format || 'Unknown'}</b></div><div><span>绑定</span><b>{resource.slot} · {resource.role}</b></div><div><span>资源 ID</span><b>{resource.resourceId || '旧清单未记录'}</b></div>{preview?.path && <div><span>导出文件</span><code title={preview.path}>{preview.path}</code></div>}</aside></div><footer><span>纹理查看器 · 工作台其他面板保持可见</span>{preview?.path && <button className="dcs-btn" onClick={() => void window.kiana?.openPath(preview.path)}>在文件夹中查看</button>}<button className="dcs-btn" onClick={onClose}>返回帧输出</button></footer></section>
}

function Inspector({ workspace, selected, selectedStage, onPreview, onNotify }: { workspace: WorkspacePayload; selected: AnalysisModule; selectedStage: CompositionStage | null; onPreview: (resource: AnalysisResource) => void; onNotify: (message: string) => void }) {
  const [tab, setTab] = useState('材质 / Shader'); const [material, setMaterial] = useState(0); const [passOpen, setPassOpen] = useState(true); const [shaderOpen, setShaderOpen] = useState(true); const [texturesOpen, setTexturesOpen] = useState(true); const [selectedTexture, setSelectedTexture] = useState(0); const textures = selectedStage ? (selectedStage.boundTextures || []) : selected.textures
  const [toolBusy, setToolBusy] = useState(''); const [toolResult, setToolResult] = useState('')
  const stageOutputs = (selectedStage?.outputResourceIds || []).map(resourceId => selected.outputs.find(resource => resource.resourceId === resourceId) || ({ resourceId, name: `EID ${selectedStage?.eventId} 输出 RID ${resourceId}`, slot: 'RT', role: '当前步骤输出', format: '实时查询', width: 0, height: 0 } as AnalysisResource))
  const materials = stageOutputs.length ? stageOutputs : selected.outputs.length ? selected.outputs : [{ name: '未记录输出资源', slot: '—', role: 'output', format: '—', width: 0, height: 0 }]
  const copyShader = async (stage: string, value: number | string) => { const text = `${stage} ${value}`; if (window.kiana) await window.kiana.copyText(text); else await navigator.clipboard.writeText(text); onNotify(`${stage} 标识已复制`) }
  const runTool = async (method: string, params: Record<string, unknown>) => { if (!window.kiana || toolBusy) return; setToolBusy(method); setToolResult(''); try { const result = await window.kiana.callRenderdoc(method, params); setToolResult(JSON.stringify(result, null, 2).slice(0, 24000)); onNotify(`${method} 完成`) } catch (error) { const message = error instanceof Error ? error.message : String(error); setToolResult(message); onNotify(message) } finally { setToolBusy('') } }
  const eventId = selectedStage?.eventId || selected.representativeEvent || selected.eventEnd
  const actionKind = selectedStage?.kind || selected.actionKind
  const actionLabel = actionKind === 'dispatch' ? 'Compute Dispatch' : actionKind === 'draw' ? 'Draw' : actionKind === 'clear' ? 'Clear Render Target' : actionKind === 'copy' ? 'Copy Resource' : actionKind === 'present' ? 'Present' : 'Pass Marker'
  return <section className="inspector panel-content"><div className="inspector-title"><b>Inspector</b><MoreVertical size={15} /></div><div className="asset-title"><div className="asset-cube"><Box size={27} /></div><div><b>{selectedStage?.name || selected.displayName}</b><span>EID {eventId}{selectedStage?.bindingName ? ` · ${selectedStage.bindingName}` : ''}</span></div></div>
    <div className="inspector-tabs">{([{ name: '基本信息', icon: Info }, { name: '材质 / Shader', icon: Layers3 }, { name: '重建映射', icon: Link2 }] as const).map(({ name, icon: Icon }) => <button title={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)} key={name}><span className="tab-glyph"><Icon size={14} strokeWidth={2.1} /></span><span>{name}</span></button>)}</div>
    {tab === '基本信息' && <div className="property-grid"><span>模块</span><b>{selected.displayName}</b><span>当前步骤</span><b>{selectedStage?.name || '代表事件'}</b><span>动作类型</span><b>{actionLabel}</b><span>置信度</span><b>{Math.round(selected.confidence * 100)}%</b><span>事件</span><b>EID {eventId}</b><span>索引数</span><b>{(selectedStage?.numIndices || selected.totalIndices).toLocaleString()}</b><span>当前输出</span><b>{materials.length}</b></div>}
    {tab === '重建映射' && <div className="mapping-list"><div><Check size={14} /><span>分析清单</span><b>{workspace.manifestPath ? '已生成' : '尚未生成'}</b></div><div><Check size={14} /><span>几何导出</span><b>{workspace.coverage.geometryExports}</b></div><div><Check size={14} /><span>证据导出</span><b>{workspace.coverage.evidenceExports}</b></div><div><Sparkles size={14} /><span>判定依据</span><b>{selected.reasons[0] || '无可用证据'}</b></div>{selected.missing.length > 0 && <div><Info size={14} /><span>缺失项</span><b>{selected.missing.join(', ')}</b></div>}</div>}
    {tab === '材质 / Shader' && <><div className="inspector-section"><button className="section-title" onClick={() => setPassOpen(value => !value)}>Pass Evidence <span>({selected.outputs.length + textures.length})</span>{passOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}</button>
      {passOpen && <div className="material-table"><div className="material-head"><span>#</span><span>类型</span><span>名称</span><span>格式</span></div>{materials.map((resource, i) => <button onClick={() => setMaterial(i)} onDoubleClick={() => onPreview(resource)} title={`${resource.name} · ${resource.format || resource.role} · 双击在中央纹理查看器中打开`} className={clsx('material-row', i === material && 'selected')} key={`${resource.name}-${i}`}><span>{i}</span><span className="resource-kind"><Database size={14} /></span><span>{resource.name}</span><span>{resource.format || resource.role}</span></button>)}</div>}</div>
    <div className="inspector-section"><button className="section-title" onClick={() => setShaderOpen(value => !value)}>Shader <span>Pass 代表 / EID 查询</span><Code2 size={13} />{shaderOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}</button>{shaderOpen && <>{actionKind === 'dispatch' ? <button className="shader-row" onClick={() => void copyShader('CS', selected.computeShader)}><span>CS</span><b>{selected.computeShader || '点击“CS 信息”查询'}</b><code>Resource ID</code></button> : <><button className="shader-row" onClick={() => void copyShader('VS', selected.vertexShader)}><span>VS</span><b>{selected.vertexShader || '未绑定'}</b><code>Resource ID</code></button><button className="shader-row" onClick={() => void copyShader('PS', selected.fragmentShader)}><span>PS</span><b>{selected.fragmentShader || '未绑定'}</b><code>Resource ID</code></button></>}<div className="renderdoc-tools"><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('get_pipeline_state', { event_id: eventId })}>管线状态</button>{actionKind === 'dispatch' ? <><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('get_shader_info', { event_id: eventId, stage: 'compute' })}>CS 信息</button><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('reverse_shader', { event_id: eventId, stage: 'compute' })}>逆向 CS</button><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('get_bound_textures', { event_id: eventId, stage: 'compute' })}>计算资源</button></> : actionKind === 'draw' ? <><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('get_shader_info', { event_id: eventId, stage: 'vertex' })}>VS 信息</button><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('get_shader_info', { event_id: eventId, stage: 'fragment' })}>PS 信息</button><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('reverse_shader', { event_id: eventId, stage: 'vertex' })}>逆向 VS</button><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('reverse_shader', { event_id: eventId, stage: 'fragment' })}>逆向 PS</button><button disabled={Boolean(toolBusy) || !eventId} onClick={() => void runTool('get_bound_textures', { event_id: eventId, stage: 'fragment' })}>绑定纹理</button></> : <span className="structural-action-note">该步骤是 {actionLabel}，没有独立 Shader。</span>}</div>{toolBusy && <div className="tool-running"><RefreshCw className="spin" size={13} />正在调用 {toolBusy}</div>}{toolResult && <pre className="tool-result">{toolResult}</pre>}</>}</div>
    <div className="inspector-section texture-list"><button className="section-title" onClick={() => setTexturesOpen(value => !value)}>当前 EID 纹理 <span>({textures.length})</span>{texturesOpen ? <ChevronDown size={13} /> : <ChevronRight size={13} />}</button>{texturesOpen && textures.slice(0, 8).map((tex, i) => <button className={clsx('texture-row', selectedTexture === i && 'selected')} onClick={() => setSelectedTexture(i)} onDoubleClick={() => onPreview(tex)} title={`${tex.name || `Resource ${tex.slot}`} · ${tex.format || 'Unknown'} · 双击在中央纹理查看器中打开`} key={tex.slot + i}><span className="resource-kind"><Layers3 size={14} /></span><b>{tex.name || `Resource ${tex.slot}`}</b><span>{tex.width || '—'} × {tex.height || '—'}</span><code>{tex.format || 'Unknown'}</code></button>)}{texturesOpen && textures.length === 0 && <div className="inspector-empty">该结构步骤没有绑定纹理</div>}</div></>}
    <div className="capture-evidence"><b>真实捕获证据</b><span>RDC {(workspace.captureBytes / 1024 / 1024).toFixed(2)} MB</span><span>{workspace.coverage.indexedActions} Indexed Actions</span><span>{workspace.coverage.frameDraws} Draw Calls</span><span>{workspace.manifestPath ? '分析清单已验证' : '等待分析清单'}</span></div></section>
}

function CaptureDialog({ onClose, onLaunch }: { onClose: () => void; onLaunch: (project: CaptureProject) => Promise<void> }) {
  const fallback: CaptureProject = { name: '自定义捕获', executablePath: '', workingDirectory: '', captureDirectory: 'E:\\KianaCaptures', arguments: '', profile: 'UnityD3D11Safe', hookChildren: true, referenceAllResources: false, captureCallstacks: false, allowFullscreen: false, captureFrame: 900, resolutionWidth: 1280, resolutionHeight: 720, windowMode: 'windowed', elevate: true, autoAnalyze: true, manualCapture: true }
  const [project, setProject] = useState<CaptureProject>(fallback)
  const [presets, setPresets] = useState<CapturePreset[]>([])
  const [launching, setLaunching] = useState(false)
  useEffect(() => { void window.kiana?.getCapturePresets().then(items => { setPresets(items); const selected = items.find(item => item.detected) || items[0]; if (selected) setProject(selected) }) }, [])
  const set = <K extends keyof CaptureProject>(key: K, value: CaptureProject[K]) => setProject(current => ({ ...current, [key]: value }))
  const browseExe = async () => { const value = await window.kiana?.selectExecutable(); if (value) { set('executablePath', value); set('workingDirectory', value.replace(/[\\/][^\\/]+$/, '')) } }
  const browseDir = async (key: 'workingDirectory' | 'captureDirectory') => { const value = await window.kiana?.selectDirectory(); if (value) set(key, value) }
  const launch = async () => { setLaunching(true); try { await onLaunch(project) } finally { setLaunching(false) } }
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="capture-dialog" role="dialog" aria-modal="true" aria-label="启动游戏并连接捕获"><header><div><Camera size={18} /><b>启动游戏并连接捕获</b></div><button onClick={onClose}><X size={17} /></button></header><div className="dialog-body">
    <div className="capture-presets">{presets.map(preset => <button key={preset.id} className={clsx(project.name === preset.name && 'selected', !preset.detected && 'missing')} onClick={() => setProject(preset)}><span className="preset-icon">{preset.id === 'zzz' ? 'Z' : 'W'}</span><span><b>{preset.name}</b><small>{preset.description}</small></span><em>{preset.detected ? '已检测' : '未安装'}</em></button>)}</div>
    <label>项目名称<input value={project.name} onChange={event => set('name', event.target.value)} /></label>
    <label>游戏可执行文件<div className="path-field"><input value={project.executablePath} onChange={event => set('executablePath', event.target.value)} /><button className="dcs-btn" onClick={browseExe}>选择…</button></div></label>
    <label>工作目录<div className="path-field"><input value={project.workingDirectory} onChange={event => set('workingDirectory', event.target.value)} /><button className="dcs-btn" onClick={() => browseDir('workingDirectory')}>选择…</button></div></label>
    <label>RDC 输出目录<div className="path-field"><input value={project.captureDirectory} onChange={event => set('captureDirectory', event.target.value)} /><button className="dcs-btn" onClick={() => browseDir('captureDirectory')}>选择…</button></div></label>
    <div className="dialog-grid"><label>捕获配置<select value={project.profile} onChange={event => set('profile', event.target.value as CaptureProject['profile'])}><option value="UnrealD3D12">Unreal D3D12</option><option value="UnityD3D11Safe">Unity D3D11 Safe</option></select></label><label>窗口模式<select value={project.windowMode} onChange={event => set('windowMode', event.target.value as CaptureProject['windowMode'])}><option value="windowed">窗口</option><option value="borderless">无边框</option><option value="fullscreen">全屏</option></select></label><label>分辨率宽<input type="number" min="640" max="7680" value={project.resolutionWidth} onChange={event => set('resolutionWidth', Number(event.target.value))} /></label><label>分辨率高<input type="number" min="480" max="4320" value={project.resolutionHeight} onChange={event => set('resolutionHeight', Number(event.target.value))} /></label><label>自动捕获 Frame<input type="number" min="1" value={project.captureFrame} onChange={event => set('captureFrame', Number(event.target.value))} disabled={project.manualCapture} /></label></div>
    <label>启动参数<input value={project.arguments} onChange={event => set('arguments', event.target.value)} /></label>
    <div className="dialog-options"><label><input type="checkbox" checked={project.hookChildren} onChange={event => set('hookChildren', event.target.checked)} />跟踪子进程</label><label><input type="checkbox" checked={project.allowFullscreen} onChange={event => set('allowFullscreen', event.target.checked)} />允许独占全屏</label><label><input type="checkbox" checked={project.referenceAllResources} onChange={event => set('referenceAllResources', event.target.checked)} />保留全部资源</label><label><input type="checkbox" checked={project.captureCallstacks} onChange={event => set('captureCallstacks', event.target.checked)} />捕获调用栈</label><label><input type="checkbox" checked={project.elevate} onChange={event => set('elevate', event.target.checked)} />管理员权限启动（UAC）</label><label><input type="checkbox" checked={project.manualCapture} onChange={event => set('manualCapture', event.target.checked)} />进入场景后手动抓帧</label><label><input type="checkbox" checked={project.autoAnalyze} onChange={event => set('autoAnalyze', event.target.checked)} />捕获后自动分析</label></div>
    {project.elevate && <p className="capture-note"><Info size={14} />启动时 Windows 会显示一次 UAC 确认；这是目标游戏要求管理员权限时完成注入所必需的。</p>}
  </div><footer><span>{project.manualCapture ? '注入后回到 Studio 点击“截取当前帧”' : `自动在 Frame ${project.captureFrame} 保存并验证 RDC`}</span><button className="dcs-btn" onClick={onClose}>取消</button><button className="dcs-btn dcs-btn--primary" disabled={launching || !project.executablePath} onClick={launch}><Play size={15} />{launching ? '启动中…' : '注入并启动游戏'}</button></footer></section></div>
}

type UtilityPanel = 'mcp' | 'preferences' | 'shortcuts' | 'docs' | 'about'

function UtilityDialog({ panel, density, scale, onDensity, onScale, onRuntime, onClose }: { panel: UtilityPanel; density: 'compact' | 'comfortable'; scale: number; onDensity: (value: 'compact' | 'comfortable') => void; onScale: (value: number) => void; onRuntime: (status: RuntimeStatus) => void; onClose: () => void }) {
  const [status, setStatus] = useState<RuntimeStatus | null>(() => window.kiana ? null : { desktop: false, connected: false, bridgeConnected: false, engineMcp: false, engineMcpUrl: 'http://127.0.0.1:8765/mcp', renderdocMcp: false, renderdocMcpUrl: 'http://127.0.0.1:8765/mcp', unityMcp: false, unityPort: 0, unityProject: '', unityVersion: '', mcpTools: 0, bridgePid: 0, kianaRoot: '浏览器交互预览', sourceRoot: '', captureCore: true, inspector: true, python: true, analysisWorker: true })
  const [refreshing, setRefreshing] = useState(false)
  const refreshRuntime = async () => { if (!window.kiana) return; setRefreshing(true); try { const next = await window.kiana.getRuntimeStatus(); setStatus(next); onRuntime(next) } finally { setRefreshing(false) } }
  useEffect(() => {
    const api = window.kiana
    if (panel !== 'mcp' || !api) return
    let active = true
    void api.getRuntimeStatus().then(next => { if (active) { setStatus(next); onRuntime(next) } })
    return () => { active = false }
  }, [panel, onRuntime])
  const titles: Record<UtilityPanel, string> = { mcp: 'MCP 与本地运行时', preferences: '界面偏好设置', shortcuts: '快捷键', docs: '调试与使用说明', about: '关于 Kiana Studio' }
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="utility-dialog" role="dialog" aria-modal="true" aria-label={titles[panel]}><header><div><Settings size={18} /><b>{titles[panel]}</b></div><button onClick={onClose} aria-label="关闭面板"><X size={17} /></button></header><div className="utility-body">
    {panel === 'mcp' && <><p>Studio 同时连接 Kiana RenderDoc 与 Unity Editor。状态来自两个真实本机端点，可用于同帧分析、重抓和重建验证。</p><div className="runtime-grid"><span>RenderDoc 安装</span><b className={status?.connected ? 'ok' : 'bad'}>{status?.connected ? '已就绪' : '未发现运行时'}</b><span>RenderDoc Bridge</span><b className={status?.bridgeConnected ? 'ok' : 'bad'}>{status?.bridgeConnected ? `在线 · PID ${status.bridgePid}` : '离线'}</b><span>RenderDoc MCP</span><b className={status?.renderdocMcp ? 'ok' : 'bad'} title={status?.renderdocMcpUrl}>{status?.renderdocMcp ? '在线 · 8765' : '正在启动'}</b><span>RenderDoc 工具</span><b className={status?.mcpTools ? 'ok' : 'bad'}>{status?.mcpTools || 0} tools</b><span>Unity Pipeline</span><b className={status?.unityMcp ? 'ok' : 'bad'}>{status?.unityMcp ? `在线 · ${status.unityPort}` : '未连接'}</b><span>Unity 版本</span><b className={status?.unityMcp ? 'ok' : 'bad'}>{status?.unityVersion || '—'}</b><span>Unity 工程</span><code title={status?.unityProject}>{status?.unityProject || '未发现运行中的工程'}</code><span>捕获核心</span><b className={status?.captureCore ? 'ok' : 'bad'}>{status?.captureCore ? '就绪' : '缺失'}</b><span>高级 Inspector</span><b className={status?.inspector ? 'ok' : 'bad'}>{status?.inspector ? '就绪' : '缺失'}</b><span>Python / 分析</span><b className={status?.python && status.analysisWorker ? 'ok' : 'bad'}>{status?.python && status.analysisWorker ? '就绪' : '需要修复'}</b><span>运行目录</span><code title={status?.kianaRoot}>{status?.kianaRoot || '检查中…'}</code><span>源码目录</span><code title={status?.sourceRoot}>{status?.sourceRoot || '检查中…'}</code></div></>}
    {panel === 'preferences' && <><div className="preference-row"><div><b>界面密度</b><span>调整场景树、Pass 列表与 Inspector 的行高。</span></div><div className="segmented"><button className={density === 'compact' ? 'active' : ''} onClick={() => onDensity('compact')}>紧凑</button><button className={density === 'comfortable' ? 'active' : ''} onClick={() => onDensity('comfortable')}>舒适</button></div></div><div className="preference-row"><div><b>界面缩放</b><span>使用 Electron 原生页面缩放，保持面板自适应。</span></div><div className="segmented">{[90,100,110,125].map(value => <button className={scale === value ? 'active' : ''} onClick={() => onScale(value)} key={value}>{value}%</button>)}</div></div></>}
    {panel === 'shortcuts' && <div className="shortcut-grid"><kbd>F12 / PrintScreen</kbd><span>保存当前帧</span><kbd>Ctrl + 0</kbd><span>重置界面缩放</span><kbd>F11</kbd><span>最大化 / 恢复视口</span><kbd>Esc</kbd><span>关闭当前浮层</span></div>}
    {panel === 'docs' && <div className="docs-copy"><b>建议工作流</b><ol><li>新建项目并选择游戏可执行文件。</li><li>选择 Unreal D3D12 或 Unity D3D11 Safe 配置启动。</li><li>进入稳定画面后按 F12 抓帧。</li><li>在帧库中选择 RDC，运行自动分析。</li><li>检查 Pass 证据、资源绑定与重建映射，再导出重建包。</li></ol><p>详细案例与排错文档随安装包放在 docs 目录中。</p></div>}
    {panel === 'about' && <div className="about-panel"><span className="about-mark">K</span><div><h2>Kiana Studio</h2><p>GPU 捕获、帧拆解与场景重建工作台</p><code>Electron Edition · {appVersion}</code></div></div>}
  </div><footer>{panel === 'mcp' && <button className="dcs-btn runtime-refresh" disabled={refreshing} onClick={() => void refreshRuntime()}><RefreshCw className={refreshing ? 'spin' : ''} size={14} />{refreshing ? '检测中…' : '重新检测'}</button>}<button className="dcs-btn dcs-btn--primary" onClick={onClose}>完成</button></footer></section></div>
}

function StatusBar({ workspace, runtime, progress, captureProgress, frame }: { workspace: WorkspacePayload; runtime: RuntimeStatus | null; progress: AnalysisProgress | null; captureProgress: CaptureProgress | null; frame: number }) {
  const percent = progress?.percent || (workspace.manifestPath ? 100 : workspace.mode === 'capture' ? 12 : 0)
  const active = captureProgress && !captureProgress.done && !captureProgress.error ? captureProgress : null
  const shownPercent = active?.percent ?? percent
  return <footer className="statusbar"><span className={clsx('connection-state', runtime?.bridgeConnected && runtime?.unityMcp && 'online')}><CircleDot size={10} />{runtime?.bridgeConnected && runtime?.unityMcp ? `RenderDoc + Unity Online · ${runtime.mcpTools}` : runtime?.bridgeConnected ? `RenderDoc MCP · ${runtime.mcpTools}` : runtime?.unityMcp ? `Unity MCP · ${runtime.unityPort}` : runtime?.connected ? 'RenderDoc Ready' : 'MCP Offline'}</span><span>API: {workspace.api}</span><span title={workspace.capturePath}>Capture: {workspace.mode === 'demo' ? 'Demo' : workspace.captureName}</span><span>Frame: {frame}</span><span className="status-grow" /><span>Draw {workspace.coverage.frameDraws}</span><span>Pass {workspace.coverage.passes}</span><span>{active?.message || progress?.message || (workspace.manifestPath ? '重建清单就绪' : workspace.mode === 'capture' ? '等待自动分析' : '等待导入 RDC')}</span><i><b style={{ width: `${shownPercent}%` }} /></i><span>{shownPercent}%</span></footer>
}

function CommandPalette({ onClose, onAction }: { onClose: () => void; onAction: (action: string) => void }) {
  const [query, setQuery] = useState('')
  const commands = ['导入 RDC', '新建捕获项目', '自动分析', '捕获 Unity 38112 基线', '打开 Unity 工程', '打开资产图谱', '打开还原合同', '打开高级 GPU 检查器', '保存工作台快照', 'MCP 连接状态', '最大化视口', '重置面板布局', '偏好设置', '快捷键', '关于 Kiana Studio']
  const filtered = commands.filter(command => command.toLowerCase().includes(query.trim().toLowerCase()))
  const runFirst = () => { if (filtered[0]) { onAction(filtered[0]); onClose() } }
  return <div className="modal-backdrop command-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="command-palette" role="dialog" aria-modal="true" aria-label="命令面板"><label><Search size={16} /><input autoFocus value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') runFirst() }} placeholder="搜索操作、面板或工作流…" /><kbd>Esc</kbd></label><div>{filtered.map((command, index) => <button key={command} onClick={() => { onAction(command); onClose() }}><span>{command}</span><kbd>{index === 0 ? 'Enter' : ''}</kbd></button>)}{filtered.length === 0 && <p>没有匹配的命令</p>}</div></section></div>
}

export default function App() {
  const savedWorkspace = useMemo(() => { try { return JSON.parse(localStorage.getItem('kiana-workspace') || '{}') } catch { return {} } }, [])
  const [workspace, setWorkspace] = useState<WorkspacePayload>(demoWorkspace); const [selected, setSelected] = useState<AnalysisModule>(() => preferredModule(demoWorkspace)); const [selectedStage, setSelectedStage] = useState<CompositionStage | null>(() => preferredStage(preferredModule(demoWorkspace))); const [runtime, setRuntime] = useState<RuntimeStatus | null>(null); const [history, setHistory] = useState<CaptureHistoryEntry[]>([]); const [progress, setProgress] = useState<AnalysisProgress | null>(null); const [captureProgress, setCaptureProgress] = useState<CaptureProgress | null>(null); const [mosaic, setMosaic] = useState<MosaicNode<PanelId> | null>(layout)
  const [captureOpen, setCaptureOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false); const [busy, setBusy] = useState(false); const [activeFrame, setActiveFrame] = useState(Number(savedWorkspace.activeFrame) || 3070); const [selectedObject, setSelectedObject] = useState(String(savedWorkspace.selectedObject || 'SM_Tower')); const [toast, setToast] = useState(''); const [focusPanel, setFocusPanel] = useState<PanelId | null>(null); const [utilityPanel, setUtilityPanel] = useState<UtilityPanel | null>(null); const [density, setDensity] = useState<'compact' | 'comfortable'>(savedWorkspace.density === 'comfortable' ? 'comfortable' : 'compact'); const [scale, setScale] = useState(Number(savedWorkspace.scale) || 100)
  const [railCollapsed, setRailCollapsed] = useState(false)
  const [openingCapturePath, setOpeningCapturePath] = useState('')
  const [resourceViewer, setResourceViewer] = useState<AnalysisResource | null>(null)
  const manuallySelectedCaptureRef = useRef('')
  const loadedCaptureRef = useRef('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(current => current === message ? '' : current), 2400) }
  const acceptWorkspace = useCallback((data: WorkspacePayload) => { const module = preferredModule(data); const stage = preferredStage(module); loadedCaptureRef.current = data.capturePath; setResourceViewer(null); setWorkspace(data); setSelected(module); setSelectedStage(stage); setActiveFrame(data.frameNumber || 0); setSelectedObject(`${stage?.name || module.displayName} · EID ${stage?.eventId || module.representativeEvent || module.eventEnd}`); setProgress(data.manifestPath ? { percent: 100, message: '重建清单就绪', done: true } : null) }, [])
  useEffect(() => {
    let runtimeChecks = 0
    const refreshRuntime = () => window.kiana?.getRuntimeStatus().then(status => { setRuntime(status); if (status.bridgeConnected) runtimeChecks = 12 }).catch(() => setRuntime(null))
    void refreshRuntime()
    const runtimeTimer = window.setInterval(() => { runtimeChecks += 1; if (runtimeChecks >= 12) window.clearInterval(runtimeTimer); else void refreshRuntime() }, 1500)
    window.kiana?.loadWorkspace().then(data => { if (data) acceptWorkspace(data) }).catch(error => notify(error instanceof Error ? error.message : '载入工作区失败'))
    window.kiana?.getCaptureHistory().then(setHistory).catch(() => setHistory([]))
    const unsubscribe = window.kiana?.onAnalysisProgress(setProgress)
    const unsubscribeCapture = window.kiana?.onCaptureProgress(update => { setCaptureProgress(update); if (update.phase === 'complete' && update.workspace) { const pinnedCapture = manuallySelectedCaptureRef.current; const alreadyLoaded = loadedCaptureRef.current.toLowerCase() === update.workspace.capturePath.toLowerCase(); if (!alreadyLoaded && (!pinnedCapture || pinnedCapture === update.workspace.capturePath)) acceptWorkspace(update.workspace); void window.kiana?.getCaptureHistory().then(setHistory); setCaptureOpen(false); setBusy(false); notify(update.message) } else if (update.phase === 'failed') { setBusy(false); notify(update.error || update.message) } })
    void window.kiana?.recoverCapture().then(async update => { if (!update || !window.kiana) return; setCaptureProgress(update); setBusy(false); const presets = await window.kiana.getCapturePresets(); const preset = presets.find(item => item.id === update.presetId || item.executablePath.toLowerCase() === update.executablePath?.toLowerCase()); if (preset) await window.kiana.launchCapture(preset) }).catch(() => undefined)
    return () => { window.clearInterval(runtimeTimer); unsubscribe?.(); unsubscribeCapture?.() }
  }, [acceptWorkspace])
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if (event.key === 'Escape') { setCaptureOpen(false); setUtilityPanel(null); setCommandOpen(false) } else if (event.ctrlKey && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(value => !value) } else if (event.key === 'F12' || event.key === 'PrintScreen') { event.preventDefault(); setCaptureOpen(true) } else if (event.key === 'F11') { event.preventDefault(); setFocusPanel(current => current === 'viewport' ? null : 'viewport') } else if (event.ctrlKey && event.key === '0') { event.preventDefault(); setScale(100); if (window.kiana) void window.kiana.setZoom(1); else document.body.style.zoom = '1' } }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut) }, [])
  const titles = useMemo(() => ({ outliner: '场景', viewport: 'RDC Viewport', timeline: 'Pass Timeline', inspector: 'Inspector' }), [])
  const importRdc = async () => { if (!window.kiana) return notify('桌面版可调用系统文件选择器'); try { const result = await window.kiana.selectRdc(); if (result) { manuallySelectedCaptureRef.current = result.capturePath; acceptWorkspace(result); notify(result.modules.length ? `已导入 ${result.captureName} 与分析清单` : `已导入 ${result.captureName}，可开始自动分析`) } } catch (error) { notify(error instanceof Error ? error.message : '导入失败') } }
  const openHistoricalCapture = async (capturePath: string) => { if (!window.kiana || openingCapturePath) return; manuallySelectedCaptureRef.current = capturePath; setOpeningCapturePath(capturePath); try { const result = await window.kiana.openCapture(capturePath); manuallySelectedCaptureRef.current = result.capturePath; acceptWorkspace(result); notify(result.modules.length ? `已打开 ${result.captureName}` : `已打开 ${result.captureName}，可开始分析`) } catch { notify('无法打开此 RDC，请检查本地文件') } finally { setOpeningCapturePath('') } }
  const openCaptureRoot = async () => { if (!window.kiana) return notify('仅桌面版可打开捕获目录'); const target = captureProgress?.outputDirectory || workspace.capturePath.replace(/[\\/][^\\/]+$/, ''); if (!target) return notify('暂无捕获总目录'); try { const error = await window.kiana.openPath(target); if (error) throw new Error(error); notify('已打开完整捕获文件夹') } catch { notify('无法打开捕获总目录') } }
  const analyze = async () => { if (busy) return; if (workspace.mode !== 'capture') return notify('请先导入一个真实 RDC 捕获'); if (!runtime?.python || !runtime.analysisWorker) return notify('Kiana Python 分析运行时尚未就绪'); setBusy(true); setProgress({ percent: 4, message: '准备分析' }); try { if (window.kiana) { const output = workspace.capturePath.replace(/\.rdc$/i, `-reconstruction-${Date.now()}`); const result = await window.kiana.runAnalysis({ capturePath: workspace.capturePath, outputDirectory: output, engine: workspace.api === 'D3D11' ? 'unity' : 'unreal', maxGeometry: 12 }); acceptWorkspace(result) } else { for (const item of [[18,'索引 Draw 与资源'],[48,'追踪纹理与 Render Target'],[72,'导出几何候选'],[96,'生成重建清单'],[100,'分析完成']] as const) { await new Promise(resolve => setTimeout(resolve, 280)); setProgress({ percent: item[0], message: item[1], done: item[0] === 100 }) } } notify('自动分析完成') } catch (error) { notify(error instanceof Error ? error.message : '分析失败') } finally { setBusy(false) } }
  const launchCapture = async (project: CaptureProject) => { try { manuallySelectedCaptureRef.current = ''; setBusy(true); setCaptureProgress({ phase: 'launching', percent: 2, message: '正在创建端到端捕获任务', projectName: project.name, executablePath: project.executablePath, outputDirectory: project.captureDirectory, api: project.profile === 'UnityD3D11Safe' ? 'D3D11' : 'D3D12', sessionActive: false }); if (window.kiana) { const result = await window.kiana.launchCapture(project); setCaptureOpen(false); setCaptureProgress(current => ({ ...current!, outputDirectory: result.outputDirectory })); notify(`游戏启动与注入任务已创建 · Worker PID ${result.pid}`) } else { setBusy(false); notify('只有桌面版能够启动真实捕获') } } catch (error) { setBusy(false); notify(error instanceof Error ? error.message : '启动失败'); throw error } }
  const triggerCapture = async () => { if (!window.kiana) return notify('只有桌面版能够触发真实抓帧'); try { manuallySelectedCaptureRef.current = ''; const result = await window.kiana.triggerCapture(); setCaptureProgress(current => ({ ...(current || {}), phase: 'capturing', percent: 45, message: '已触发当前帧，正在写入 RDC' })); notify(`已触发当前帧 · ${result.outputDirectory}`) } catch (error) { notify(error instanceof Error ? error.message : '触发抓帧失败') } }
  const exportPackage = async () => { if (workspace.mode !== 'capture' || !workspace.manifestPath) return notify('请先导入真实 RDC 并完成自动分析'); if (window.kiana) { try { await window.kiana.openPath(workspace.packageDirectory); notify('已打开真实分析包目录') } catch (error) { notify(error instanceof Error ? error.message : '无法打开目录') } } else notify(`分析包：${workspace.packageDirectory}`) }
  const openArtifact = async (path: string | undefined, label: string) => { if (!path) return notify(`${label}尚未生成，请重新运行自动分析`); try { await window.kiana?.openPath(path); notify(`已打开${label}`) } catch (error) { notify(error instanceof Error ? error.message : `无法打开${label}`) } }
  const saveSnapshot = async () => { if (!window.kiana) return notify('桌面版可保存工作台快照'); try { const result = await window.kiana.saveViewportScreenshot(); if (result) notify(`工作台快照已保存 · ${result}`) } catch (error) { notify(error instanceof Error ? error.message : '快照保存失败') } }
  const captureUnityBaseline = async () => { if (!window.kiana) return notify('桌面版可连接 Unity Pipeline'); if (!runtime?.unityMcp || !runtime.unityProject) return notify('Unity Editor 尚未连接'); try { const response = await window.kiana.callUnity('eval', { code: 'return Kiana.Frame38112.BuildFinalCompositeStage.Capture();' }, runtime.unityProject) as any; const relative = String(response?.data?.result?.result || 'Assets/Kiana/Validation/FinalComposite-Stage2475-TEMP.png'); const saved = `${runtime.unityProject.replace(/[\\/]$/, '')}\\${relative.replace(/\//g, '\\')}`; notify(`Unity 38112 基线已更新 · ${saved}`) } catch (error) { notify(error instanceof Error ? error.message : 'Unity 基线捕获失败') } }
  const openUnityProject = async () => { if (!window.kiana || !runtime?.unityProject) return notify('没有检测到 Unity 工程'); try { const error = await window.kiana.openPath(runtime.unityProject); if (error) throw new Error(error); notify('已打开 Unity 38112 工程目录') } catch (error) { notify(error instanceof Error ? error.message : '无法打开 Unity 工程') } }
  const applyScale = async (value: number) => { setScale(value); if (window.kiana) await window.kiana.setZoom(value / 100); else document.body.style.zoom = String(value / 100) }
  const menuAction = async (action: string) => { if (action === '新建捕获项目') setCaptureOpen(true); else if (action === '导入 RDC') await importRdc(); else if (action === '自动分析') await analyze(); else if (action === '捕获 Unity 38112 基线') await captureUnityBaseline(); else if (action === '打开 Unity 工程') await openUnityProject(); else if (action === '打开资产图谱') await openArtifact(workspace.assetGraph?.path, '资产图谱'); else if (action === '打开还原合同') await openArtifact(workspace.reconstructionContract?.path, '还原合同'); else if (action === '保存工作台快照') await saveSnapshot(); else if (action === '保存工作区') { localStorage.setItem('kiana-workspace', JSON.stringify({ activeFrame, selectedObject, density, scale })); notify('工作区状态已保存') } else if (action === '复制事件路径') { const value = `${workspace.capturePath}#EID=${selected.representativeEvent || selected.eventEnd}`; if (window.kiana) await window.kiana.copyText(value); else await navigator.clipboard.writeText(value); notify('事件路径已复制') } else if (action === '重置面板布局') { setMosaic(layout); setFocusPanel(null) } else if (action === '最大化视口') setFocusPanel('viewport'); else if (action === '场景浏览器') setFocusPanel(current => current === 'outliner' ? null : 'outliner'); else if (action === '切换紧凑密度') setDensity(value => value === 'compact' ? 'comfortable' : 'compact'); else if (action === '打开高级 GPU 检查器') { if (workspace.mode !== 'capture') notify('请先导入真实 RDC，再打开高级 Inspector'); else if (window.kiana) await window.kiana.openInspector(workspace.capturePath); else notify('桌面版会打开 Kiana RenderDoc Inspector') } else if (action === 'MCP 连接状态') setUtilityPanel('mcp'); else if (action === '偏好设置') setUtilityPanel('preferences'); else if (action === '快捷键') setUtilityPanel('shortcuts'); else if (action === '调试文档') setUtilityPanel('docs'); else if (action === '关于 Kiana Studio') setUtilityPanel('about'); else if (action === '最小化') window.kiana?.minimize(); else if (action === '最大化') window.kiana?.maximize() }
  const selectModule = (module: AnalysisModule) => { const stage = preferredStage(module); setSelected(module); setSelectedStage(stage); setSelectedObject(`${stage?.name || module.displayName} · EID ${stage?.eventId || module.representativeEvent || module.eventEnd}`); notify(`定位到 EID ${stage?.eventId || module.representativeEvent || module.eventEnd}`) }
  const selectObject = (name: string, module?: AnalysisModule) => { setSelectedObject(name); if (module) selectModule(module); else notify(`已选择 ${name}`) }
  const renderPanel = (id: PanelId) => id === 'outliner' ? <SceneOutliner workspace={workspace} selected={selectedObject} onSelect={selectObject} /> : id === 'viewport' ? <Viewport key={workspace.capturePath} workspace={workspace} selected={selected} selectedStage={selectedStage} selectedObject={selectedObject} frame={activeFrame} maximized={focusPanel === 'viewport'} resource={resourceViewer} onCloseResource={() => setResourceViewer(null)} onMaximize={() => setFocusPanel(current => current === 'viewport' ? null : 'viewport')} onSnapshot={() => void saveSnapshot()} onNotify={notify} /> : id === 'timeline' ? <Timeline key={workspace.capturePath} workspace={workspace} selected={selected} selectedStage={selectedStage} frame={activeFrame} onSelect={selectModule} onSelectStage={stage => { setSelectedStage(stage); setSelectedObject(`${stage.name} · EID ${stage.eventId}`); notify(`已锁定 EID ${stage.eventId} 的真实输出`) }} /> : <Inspector key={`${workspace.capturePath}:${selectedStage?.eventId || selected.representativeEvent || selected.eventEnd}`} workspace={workspace} selected={selected} selectedStage={selectedStage} onPreview={resource => { setResourceViewer(resource); notify(`已在纹理查看器打开 ${resource.name}`) }} onNotify={notify} />
  const captureArmed = Boolean(captureProgress?.sessionActive) && !(captureProgress?.phase === 'capturing' && captureProgress.message.includes('已触发'))
  return <div className="dcs kiana-app" data-dcs-density={density} data-dcs-accent="cyan" data-dcs-dark="darker"><TitleBar onAction={menuAction} onCommand={() => setCommandOpen(true)} runtime={runtime} workspace={workspace} /><Pipeline workspace={workspace} runtime={runtime} progress={captureProgress && !captureProgress.done ? captureProgress : progress} captureArmed={captureArmed} busy={busy} onCapture={() => setCaptureOpen(true)} onTrigger={() => void triggerCapture()} onAnalyze={analyze} onExport={exportPackage} /><main className={clsx('workbench', railCollapsed && 'rail-collapsed')}><ProjectRail workspace={workspace} history={history} collapsed={railCollapsed} openingCapturePath={openingCapturePath} onToggle={() => setRailCollapsed(value => !value)} onImport={importRdc} onNew={() => setCaptureOpen(true)} onOpenPackage={() => void exportPackage()} onOpenAssetGraph={() => void openArtifact(workspace.assetGraph?.path, '资产图谱')} onOpenContract={() => void openArtifact(workspace.reconstructionContract?.path, '还原合同')} onOpenCapture={capturePath => void openHistoricalCapture(capturePath)} onOpenCaptureRoot={() => void openCaptureRoot()} onSelectModule={selectModule} activeFrame={activeFrame} /><div className="mosaic-host"><Mosaic<PanelId> value={focusPanel || mosaic} onChange={value => { if (!focusPanel) setMosaic(value) }} renderTile={(id, path) => <MosaicWindow<PanelId> path={path} title={titles[id]} toolbarControls={[]} renderPreview={() => <div />}><div className={`panel panel-${id}`}>{renderPanel(id)}</div></MosaicWindow>} /></div></main><StatusBar workspace={workspace} runtime={runtime} progress={progress} captureProgress={captureProgress} frame={activeFrame} />{captureOpen && <CaptureDialog onClose={() => setCaptureOpen(false)} onLaunch={launchCapture} />}{utilityPanel && <UtilityDialog panel={utilityPanel} density={density} scale={scale} onDensity={setDensity} onScale={value => void applyScale(value)} onRuntime={setRuntime} onClose={() => setUtilityPanel(null)} />}{commandOpen && <CommandPalette onClose={() => setCommandOpen(false)} onAction={action => void menuAction(action)} />}{toast && <div className="studio-toast"><Check size={15} />{toast}</div>}</div>
}
